=== albotw/CovidTracker_modelisation/xml/structureXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT data              (date, tests, hospitalises)>
<!ELEMENT date              (#PCDATA)>
<!ELEMENT tests             (test+)>
<!ELEMENT hospitalises      (reanimation+, retour_domicile+, decede+)>
<!ELEMENT test              (positifs, total)>
<!ELEMENT positifs          (#PCDATA)>
<!ELEMENT nouveaux          (#PCDATA)>
<!ELEMENT total             (#PCDATA)>
<!ELEMENT reanimation       (total, nouveaux)>
<!ELEMENT retour_domicile   (total, nouveaux)>
<!ELEMENT decede            (total, nouveaux)>

<!ATTLIST test scale            (france|departement|region) #REQUIRED>
<!ATTLIST test region           CDATA #IMPLIED>
<!ATTLIST test departement      CDATA #IMPLIED>

<!ATTLIST reanimation scale             (france|departement|region) #REQUIRED >
<!ATTLIST reanimation region            CDATA #IMPLIED >
<!ATTLIST reanimation departement       CDATA #IMPLIED >

<!ATTLIST retour_domicile scale         (france|departement|region) #REQUIRED >
<!ATTLIST retour_domicile region        CDATA #IMPLIED >
<!ATTLIST retour_domicile departement   CDATA #IMPLIED >

<!ATTLIST decede scale         (france|departement|region) #REQUIRED >
<!ATTLIST decede region        CDATA #IMPLIED >
<!ATTLIST decede departement   CDATA #IMPLIED >

=== albotw/CovidTracker_modelisation/xml/structureXML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE data SYSTEM 'structureXML.dtd'>
<data>
    <date>12/12/2020</date>

    <tests>
        <test scale="region" region="FR-CVL">
            <positifs>190</positifs>
            <total>1400</total>
        </test>

        <test scale="france">
            <positifs>54110</positifs>
            <total>140000</total>
        </test>

        <test scale="departement" departement="58">
            <positifs>400</positifs>
            <total>1000</total>
        </test>
    </tests>

    <hospitalises>

        <reanimation scale="region" region="FR-ARA">
            <total>7600</total>
            <nouveaux>35</nouveaux>
        </reanimation>

        <retour_domicile scale="france">
            <total>7800</total>
            <nouveaux>40</nouveaux>
        </retour_domicile>

        <decede scale="departement" departement="21" >
            <total></total>
            <nouveaux></nouveaux>
        </decede>

    </hospitalises>
</data>
